[package]
name = "repository"
version = "0.1.0"
edition = "2021"

[dependencies]
environment = { path = "../environment" }
errors = { path = "../errors" }
database = { path = "../database" }
model = { path = "../model" }
async-trait = "0.1.85"
serde_json = "1.0.138"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"


[dev-dependencies]
tokio = { version = "1", features = ["full"] }
errors = { path = "../errors" }
surrealdb = "2.1.4"
chrono = "0.4.39"
serde_json = "1.0.138"
serde = "1.0"
