[package]
name = "controller"
version = "0.1.0"
edition = "2021"

[dependencies]
environment = { path = "../environment" }
errors = { path = "../errors" }
database = { path = "../database" }
repository = { path = "../repository" }
service = { path = "../service" }
state = { path = "../state" }
model = { path = "../model" }

axum = {version = "0.7.5",features = ["multipart"] }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
axum-extra = { version = "0.9.0", features = ["cookie"] }
uuid = { version = "1.3.0", features = ["serde", "v4"] }
validator = { version = "0.20", features = ["derive"] }
redis = { version = "0.27.4", features = ["tokio-comp"] }
argon2 = "0.5.0"
time = "0.3.20"
utoipa = { version = "5", features = ["axum_extras"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"



